<a href="https://colab.research.google.com/github/jebin24it-boop/Infotact_Travel_Hospitality_Analytics/blob/Saurav-Data_Cleaning/notebooks/Day3_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import pandas as pd
import numpy as np

In [55]:
df=pd.read_csv('Hotel Reservations.csv')

In [56]:
df['booking_status']

0        1
1        1
2        0
3        0
4        0
        ..
36270    1
36271    0
36272    1
36273    0
36274    1
Name: booking_status, Length: 36275, dtype: int64

In [57]:
df['booking_status'].astype(str)

0        1
1        1
2        0
3        0
4        0
        ..
36270    1
36271    0
36272    1
36273    0
36274    1
Name: booking_status, Length: 36275, dtype: object

In [58]:
#Converting the status of booking to binary values and Canceled :0 and Not canceled as 1
status_mapping = {'Not_Canceled': 1, 'Canceled': 0}
df['booking_status'] = df['booking_status'].replace(status_mapping)
print("Booking status column converted to binary.")

Booking status column converted to binary.

In [59]:
print(df['booking_status'].value_counts())
print("Booking status column verified.")
print(df['booking_status'])

booking_status
1    24390
0    11885
Name: count, dtype: int64
Booking status column verified.
0        1
1        1
2        0
3        0
4        0
        ..
36270    1
36271    0
36272    1
36273    0
36274    1
Name: booking_status, Length: 36275, dtype: int64

In [60]:
print(df['booking_status'].isnull().sum())

0

In [61]:
df['market_segment_type'].unique()

array(['Offline', 'Online', 'Corporate', 'Aviation', 'Complementary'],
      dtype=object)

In [62]:
nan_columns = df.isnull().sum()
nan_columns = nan_columns[nan_columns > 0]

if not nan_columns.empty:
    print("Columns with NaN values and their counts:")
    print(nan_columns)
else:
    print("No columns with NaN values found in the DataFrame.")

No columns with NaN values found in the DataFrame.

In [63]:
# Identify object-type columns and display unique values
object_cols = df.select_dtypes(include=['object']).columns

print(f"Categorical columns (object type): {list(object_cols)}\n")

for col in object_cols:
    unique_vals = df[col].unique()
    print(f"Unique values in '{col}' ({len(unique_vals)} values):")
    print(unique_vals)
    print("-" * 30)

Categorical columns (object type): ['Booking_ID', 'type_of_meal_plan', 'room_type_reserved', 'market_segment_type']

Unique values in 'Booking_ID' (36275 values):
['INN00001' 'INN00002' 'INN00003' ... 'INN36273' 'INN36274' 'INN36275']
------------------------------
Unique values in 'type_of_meal_plan' (4 values):
['Meal Plan 1' 'Not Selected' 'Meal Plan 2' 'Meal Plan 3']
------------------------------
Unique values in 'room_type_reserved' (7 values):
['Room_Type 1' 'Room_Type 4' 'Room_Type 2' 'Room_Type 6' 'Room_Type 5'
 'Room_Type 7' 'Room_Type 3']
------------------------------
Unique values in 'market_segment_type' (5 values):
['Offline' 'Online' 'Corporate' 'Aviation' 'Complementary']
------------------------------

In [64]:
df.dtypes

Booking_ID                               object
no_of_adults                              int64
no_of_children                            int64
no_of_weekend_nights                      int64
no_of_week_nights                         int64
type_of_meal_plan                        object
required_car_parking_space                int64
room_type_reserved                       object
lead_time                                 int64
arrival_year                              int64
arrival_month                             int64
arrival_date                              int64
market_segment_type                      object
repeated_guest                            int64
no_of_previous_cancellations              int64
no_of_previous_bookings_not_canceled      int64
avg_price_per_room                      float64
no_of_special_requests                    int64
booking_status                            int64
dtype: object