<a href="https://colab.research.google.com/github/jebin24it-boop/Infotact_Travel_Hospitality_Analytics/blob/Saurav-Data_Cleaning/notebooks/Day4_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
import numpy as np

In [43]:
df=pd.read_csv('Hotel Reservations.csv')

In [44]:
df

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,1
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,1
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,0
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,0
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,INN36271,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,2018,8,3,Online,0,0,0,167.80,1,1
36271,INN36272,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,2018,10,17,Online,0,0,0,90.95,2,0
36272,INN36273,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,2018,7,1,Online,0,0,0,98.39,2,1
36273,INN36274,2,0,0,3,Not Selected,0,Room_Type 1,63,2018,4,21,Online,0,0,0,94.50,0,0
36274,INN36275,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,2018,12,30,Offline,0,0,0,161.67,0,1

In [45]:
#Feature Enginrring :Handling date and time features
df['arrival_date_full'] = df['arrival_date'].astype(str).str.zfill(2) + '-' + \
                          df['arrival_month'].astype(str).str.zfill(2) + '-' + \
                          df['arrival_year'].astype(str)

In [46]:
#Drop the original seprate date columns as they are now combined
df=df.drop(columns=['arrival_year','arrival_month','arrival_date'])

In [47]:
df['arrival_date_full']

0        02-10-2017
1        06-11-2018
2        28-02-2018
3        20-05-2018
4        11-04-2018
            ...
36270    03-08-2018
36271    17-10-2018
36272    01-07-2018
36273    21-04-2018
36274    30-12-2018
Name: arrival_date_full, Length: 36275, dtype: object

In [48]:
df['arrival_date_full']

0        02-10-2017
1        06-11-2018
2        28-02-2018
3        20-05-2018
4        11-04-2018
            ...
36270    03-08-2018
36271    17-10-2018
36272    01-07-2018
36273    21-04-2018
36274    30-12-2018
Name: arrival_date_full, Length: 36275, dtype: object

In [50]:
df.to_csv('Hotel_Reservations.csv')