<a href="https://colab.research.google.com/github/jebin24it-boop/Infotact_Travel_Hospitality_Analytics/blob/Saurav-Data_Cleaning/notebooks/Day5_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Hotel_Reservations.csv')

In [3]:
df

,Unnamed: 0,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,...,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status,arrival_date_full
0,0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,...,10,2,Offline,0,0,0,65.00,0,1,02-10-2017
1,1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,...,11,6,Online,0,0,0,106.68,1,1,06-11-2018
2,2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,...,2,28,Online,0,0,0,60.00,0,0,28-02-2018
3,3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,...,5,20,Online,0,0,0,100.00,0,0,20-05-2018
4,4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,...,4,11,Online,0,0,0,94.50,0,0,11-04-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,36270,INN36271,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,...,8,3,Online,0,0,0,167.80,1,1,03-08-2018
36271,36271,INN36272,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,...,10,17,Online,0,0,0,90.95,2,0,17-10-2018
36272,36272,INN36273,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,...,7,1,Online,0,0,0,98.39,2,1,01-07-2018
36273,36273,INN36274,2,0,0,3,Not Selected,0,Room_Type 1,63,...,4,21,Online,0,0,0,94.50,0,0,21-04-2018
36274,36274,INN36275,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,...,12,30,Offline,0,0,0,161.67,0,1,30-12-2018

In [5]:
df['room_type_reserved'].unique()

array(['Room_Type 1', 'Room_Type 4', 'Room_Type 2', 'Room_Type 6',
       'Room_Type 5', 'Room_Type 7', 'Room_Type 3'], dtype=object)

In [7]:
df['type_of_meal_plan'].unique()

array(['Meal Plan 1', 'Not Selected', 'Meal Plan 2', 'Meal Plan 3'],
      dtype=object)

In [8]:
# Define mapping for room types
room_type_mapping = {
    'Room_Type 1': 'Standard Room',
    'Room_Type 4': 'Family Room',
    'Room_Type 2': 'Deluxe Room',
    'Room_Type 6': 'Studio Room',
    'Room_Type 5': 'Executive Room',
    'Room_Type 7': 'Presidential Suite',
    'Room_Type 3': 'Suite'
}

# Define mapping for meal plans
meal_plan_mapping = {
    'Meal Plan 1': 'Breakfast, Lunch & Dinner',
    'Not Selected': 'No Meal Plan',
    'Meal Plan 2': 'Breakfast & Dinner',
    'Meal Plan 3': 'Breakfast Only'
}

# Create new 'descriptive_room_type' column
df['descriptive_room_type'] = df['room_type_reserved'].map(room_type_mapping)

# Create new 'descriptive_meal_plan' column
df['descriptive_meal_plan'] = df['type_of_meal_plan'].map(meal_plan_mapping)

print('New descriptive columns added. Displaying a sample:')
display(df[['room_type_reserved', 'descriptive_room_type', 'type_of_meal_plan', 'descriptive_meal_plan']].head())

New descriptive columns added. Displaying a sample:

,room_type_reserved,descriptive_room_type,type_of_meal_plan,descriptive_meal_plan
0,Room_Type 1,Standard Room,Meal Plan 1,"Breakfast, Lunch & Dinner"
1,Room_Type 1,Standard Room,Not Selected,No Meal Plan
2,Room_Type 1,Standard Room,Meal Plan 1,"Breakfast, Lunch & Dinner"
3,Room_Type 1,Standard Room,Meal Plan 1,"Breakfast, Lunch & Dinner"
4,Room_Type 1,Standard Room,Not Selected,No Meal Plan

In [9]:
df.shape

(36275, 23)

In [10]:
df

,Unnamed: 0,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,...,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status,arrival_date_full,descriptive_room_type,descriptive_meal_plan
0,0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,...,Offline,0,0,0,65.00,0,1,02-10-2017,Standard Room,"Breakfast, Lunch & Dinner"
1,1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,...,Online,0,0,0,106.68,1,1,06-11-2018,Standard Room,No Meal Plan
2,2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,...,Online,0,0,0,60.00,0,0,28-02-2018,Standard Room,"Breakfast, Lunch & Dinner"
3,3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,...,Online,0,0,0,100.00,0,0,20-05-2018,Standard Room,"Breakfast, Lunch & Dinner"
4,4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,...,Online,0,0,0,94.50,0,0,11-04-2018,Standard Room,No Meal Plan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,36270,INN36271,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,...,Online,0,0,0,167.80,1,1,03-08-2018,Family Room,"Breakfast, Lunch & Dinner"
36271,36271,INN36272,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,...,Online,0,0,0,90.95,2,0,17-10-2018,Standard Room,"Breakfast, Lunch & Dinner"
36272,36272,INN36273,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,...,Online,0,0,0,98.39,2,1,01-07-2018,Standard Room,"Breakfast, Lunch & Dinner"
36273,36273,INN36274,2,0,0,3,Not Selected,0,Room_Type 1,63,...,Online,0,0,0,94.50,0,0,21-04-2018,Standard Room,No Meal Plan
36274,36274,INN36275,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,...,Offline,0,0,0,161.67,0,1,30-12-2018,Standard Room,"Breakfast, Lunch & Dinner"

In [11]:
print('Value counts for descriptive_room_type:')
display(df['descriptive_room_type'].value_counts())

print('\nValue counts for descriptive_meal_plan:')
display(df['descriptive_meal_plan'].value_counts())

Value counts for descriptive_room_type:

descriptive_room_type
Standard Room         28130
Family Room            6057
Studio Room             966
Deluxe Room             692
Executive Room          265
Presidential Suite      158
Suite                     7
Name: count, dtype: int64

Value counts for descriptive_meal_plan:

descriptive_meal_plan
Breakfast, Lunch & Dinner    27835
No Meal Plan                  5130
Breakfast & Dinner            3305
Breakfast Only                   5
Name: count, dtype: int64

In [12]:
print('Missing values per column:')
display(df.isnull().sum().sort_values(ascending=False))

Missing values per column:

Unnamed: 0                              0
Booking_ID                              0
no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
booking_status                          0
arrival_date_full                       0
descriptive_room_type                   0
descriptive_meal_plan                   0
dtype: int64

In [13]:
print('DataFrame Info (Data Types and Non-Null Counts):')
display(df.info())

DataFrame Info (Data Types and Non-Null Counts):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 23 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Unnamed: 0                            36275 non-null  int64
 1   Booking_ID                            36275 non-null  object
 2   no_of_adults                          36275 non-null  int64
 3   no_of_children                        36275 non-null  int64
 4   no_of_weekend_nights                  36275 non-null  int64
 5   no_of_week_nights                     36275 non-null  int64
 6   type_of_meal_plan                     36275 non-null  object
 7   required_car_parking_space            36275 non-null  int64
 8   room_type_reserved                    36275 non-null  object
 9   lead_time                             36275 non-null  int64
 10  arrival_year                          36275 non-null  int64
 11  arrival_month                         36275 non-null  int64
 12  arrival_date                          36275 non-null  int64
 13  market_segment_type                   36275 non-null  object
 14  repeated_guest                        36275 non-null  int64
 15  no_of_previous_cancellations          36275 non-null  int64
 16  no_of_previous_bookings_not_canceled  36275 non-null  int64
 17  avg_price_per_room                    36275 non-null  float64
 18  no_of_special_requests                36275 non-null  int64
 19  booking_status                        36275 non-null  int64
 20  arrival_date_full                     36275 non-null  object
 21  descriptive_room_type                 36275 non-null  object
 22  descriptive_meal_plan                 36275 non-null  object
dtypes: float64(1), int64(15), object(7)
memory usage: 6.4+ MB

None

In [14]:
# Convert 'arrival_date_full' to datetime objects
df['arrival_date_full'] = pd.to_datetime(df['arrival_date_full'], format='%d-%m-%Y', errors='coerce')

print("Converted 'arrival_date_full' to datetime.")

Converted 'arrival_date_full' to datetime.

In [15]:
# Drop the 'Unnamed: 0' column if it exists and is redundant
if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'])
    print("Dropped 'Unnamed: 0' column.")
else:
    print("'Unnamed: 0' column not found.")

Dropped 'Unnamed: 0' column.

In [16]:
# Display info again to confirm changes
print('\nDataFrame Info after type conversion and column drop:')
display(df.info())

DataFrame Info after type conversion and column drop:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 22 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            36275 non-null  object
 1   no_of_adults                          36275 non-null  int64
 2   no_of_children                        36275 non-null  int64
 3   no_of_weekend_nights                  36275 non-null  int64
 4   no_of_week_nights                     36275 non-null  int64
 5   type_of_meal_plan                     36275 non-null  object
 6   required_car_parking_space            36275 non-null  int64
 7   room_type_reserved                    36275 non-null  object
 8   lead_time                             36275 non-null  int64
 9   arrival_year                          36275 non-null  int64
 10  arrival_month                         36275 non-null  int64
 11  arrival_date                          36275 non-null  int64
 12  market_segment_type                   36275 non-null  object
 13  repeated_guest                        36275 non-null  int64
 14  no_of_previous_cancellations          36275 non-null  int64
 15  no_of_previous_bookings_not_canceled  36275 non-null  int64
 16  avg_price_per_room                    36275 non-null  float64
 17  no_of_special_requests                36275 non-null  int64
 18  booking_status                        36275 non-null  int64
 19  arrival_date_full                     36238 non-null  datetime64[ns]
 20  descriptive_room_type                 36275 non-null  object
 21  descriptive_meal_plan                 36275 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(14), object(6)
memory usage: 6.1+ MB

None

In [17]:
# Identify and count NaT values in 'arrival_date_full'
nat_count = df['arrival_date_full'].isnull().sum()
print(f"Number of NaT values in 'arrival_date_full': {nat_count}")

# Drop rows where 'arrival_date_full' is NaT
df = df.dropna(subset=['arrival_date_full'])
print(f"Dropped {nat_count} rows with NaT values in 'arrival_date_full'.")

Number of NaT values in 'arrival_date_full': 37
Dropped 37 rows with NaT values in 'arrival_date_full'.

In [18]:
# Display info again to confirm all 'arrival_date_full' values are non-null
print('\nDataFrame Info after dropping NaT values:')
display(df.info())

DataFrame Info after dropping NaT values:
<class 'pandas.core.frame.DataFrame'>
Index: 36238 entries, 0 to 36274
Data columns (total 22 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            36238 non-null  object
 1   no_of_adults                          36238 non-null  int64
 2   no_of_children                        36238 non-null  int64
 3   no_of_weekend_nights                  36238 non-null  int64
 4   no_of_week_nights                     36238 non-null  int64
 5   type_of_meal_plan                     36238 non-null  object
 6   required_car_parking_space            36238 non-null  int64
 7   room_type_reserved                    36238 non-null  object
 8   lead_time                             36238 non-null  int64
 9   arrival_year                          36238 non-null  int64
 10  arrival_month                         36238 non-null  int64
 11  arrival_date                          36238 non-null  int64
 12  market_segment_type                   36238 non-null  object
 13  repeated_guest                        36238 non-null  int64
 14  no_of_previous_cancellations          36238 non-null  int64
 15  no_of_previous_bookings_not_canceled  36238 non-null  int64
 16  avg_price_per_room                    36238 non-null  float64
 17  no_of_special_requests                36238 non-null  int64
 18  booking_status                        36238 non-null  int64
 19  arrival_date_full                     36238 non-null  datetime64[ns]
 20  descriptive_room_type                 36238 non-null  object
 21  descriptive_meal_plan                 36238 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(14), object(6)
memory usage: 6.4+ MB

None

In [19]:
df.shape

(36238, 22)

In [20]:
df

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,...,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status,arrival_date_full,descriptive_room_type,descriptive_meal_plan
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,...,Offline,0,0,0,65.00,0,1,2017-10-02,Standard Room,"Breakfast, Lunch & Dinner"
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,...,Online,0,0,0,106.68,1,1,2018-11-06,Standard Room,No Meal Plan
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,...,Online,0,0,0,60.00,0,0,2018-02-28,Standard Room,"Breakfast, Lunch & Dinner"
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,...,Online,0,0,0,100.00,0,0,2018-05-20,Standard Room,"Breakfast, Lunch & Dinner"
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,...,Online,0,0,0,94.50,0,0,2018-04-11,Standard Room,No Meal Plan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,INN36271,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,2018,...,Online,0,0,0,167.80,1,1,2018-08-03,Family Room,"Breakfast, Lunch & Dinner"
36271,INN36272,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,2018,...,Online,0,0,0,90.95,2,0,2018-10-17,Standard Room,"Breakfast, Lunch & Dinner"
36272,INN36273,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,2018,...,Online,0,0,0,98.39,2,1,2018-07-01,Standard Room,"Breakfast, Lunch & Dinner"
36273,INN36274,2,0,0,3,Not Selected,0,Room_Type 1,63,2018,...,Online,0,0,0,94.50,0,0,2018-04-21,Standard Room,No Meal Plan
36274,INN36275,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,2018,...,Offline,0,0,0,161.67,0,1,2018-12-30,Standard Room,"Breakfast, Lunch & Dinner"

In [21]:
df.to_csv('Hotel_Reservations_1.csv')