<a href="https://colab.research.google.com/github/jebin24it-boop/Infotact_Travel_Hospitality_Analytics/blob/Saurav-Data_Cleaning/notebooks/Day6_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
# Load the partially cleaned dataset
df = pd.read_csv('Hotel_Reservations_1.csv')
display(df.head())

,Unnamed: 0,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,...,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status,arrival_date_full,descriptive_room_type,descriptive_meal_plan,total_guests,total_nights
0,0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,...,0,0,65.00,0,1,02-10-2017,Standard Room,"Breakfast, Lunch & Dinner",2,3
1,1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,...,0,0,106.68,1,1,06-11-2018,Standard Room,No Meal Plan,2,5
2,2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,...,0,0,60.00,0,0,28-02-2018,Standard Room,"Breakfast, Lunch & Dinner",1,3
3,3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,...,0,0,100.00,0,0,20-05-2018,Standard Room,"Breakfast, Lunch & Dinner",2,2
4,4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,...,0,0,94.50,0,0,11-04-2018,Standard Room,No Meal Plan,2,2

In [4]:
# Drop the 'Unnamed: 0' column if it exists and is redundant
if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'])
    print("Dropped 'Unnamed: 0' column.")
else:
    print("'Unnamed: 0' column not found or already dropped.")

Dropped 'Unnamed: 0' column.

In [5]:
initial_rows = df.shape[0]
invalid_date_rows_to_drop = df[df['arrival_date_full'] == '29-02-2018'].shape[0]
df = df[df['arrival_date_full'] != '29-02-2018']
print(f"Dropped {invalid_date_rows_to_drop} rows with invalid date '29-02-2018'.")
print(f"Remaining rows: {df.shape[0]}")

Dropped 37 rows with invalid date '29-02-2018'.
Remaining rows: 36238

In [6]:
zero_nights_rows_to_drop = df[df['total_nights'] == 0].shape[0]
df = df[df['total_nights'] != 0]
print(f"Dropped {zero_nights_rows_to_drop} rows with zero total nights.")
print(f"Remaining rows: {df.shape[0]}")

Dropped 78 rows with zero total nights.
Remaining rows: 36160

In [7]:
children_outlier_rows_to_drop = df[df['no_of_children'] > 3].shape[0]
df = df[df['no_of_children'] <= 3]
print(f"Dropped {children_outlier_rows_to_drop} rows with more than 3 children.")
print(f"Remaining rows: {df.shape[0]}")

Dropped 3 rows with more than 3 children.
Remaining rows: 36157

In [8]:
print('Final DataFrame shape:', df.shape)
print('\nFinal DataFrame Info:')
display(df.info())

Final DataFrame shape: (36157, 24)

Final DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 36157 entries, 0 to 36274
Data columns (total 24 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            36157 non-null  object
 1   no_of_adults                          36157 non-null  int64
 2   no_of_children                        36157 non-null  int64
 3   no_of_weekend_nights                  36157 non-null  int64
 4   no_of_week_nights                     36157 non-null  int64
 5   type_of_meal_plan                     36157 non-null  object
 6   required_car_parking_space            36157 non-null  int64
 7   room_type_reserved                    36157 non-null  object
 8   lead_time                             36157 non-null  int64
 9   arrival_year                          36157 non-null  int64
 10  arrival_month                         36157 non-null  int64
 11  arrival_date                          36157 non-null  int64
 12  market_segment_type                   36157 non-null  object
 13  repeated_guest                        36157 non-null  int64
 14  no_of_previous_cancellations          36157 non-null  int64
 15  no_of_previous_bookings_not_canceled  36157 non-null  int64
 16  avg_price_per_room                    36157 non-null  float64
 17  no_of_special_requests                36157 non-null  int64
 18  booking_status                        36157 non-null  int64
 19  arrival_date_full                     36157 non-null  object
 20  descriptive_room_type                 36157 non-null  object
 21  descriptive_meal_plan                 36157 non-null  object
 22  total_guests                          36157 non-null  int64
 23  total_nights                          36157 non-null  int64
dtypes: float64(1), int64(16), object(7)
memory usage: 6.9+ MB

None

In [9]:
condition = (df['avg_price_per_room'] == 0) & ((df['total_guests'] == 0) | ((df['no_of_adults'] == 0) & (df['no_of_children'] == 0)))
filtered_df = df[condition]

print(f"Number of rows with avg_price_per_room = 0 AND (total_guests = 0 OR (no_of_adults = 0 AND no_of_children = 0)): {filtered_df.shape[0]}")
display(filtered_df.head())

Number of rows with avg_price_per_room = 0 AND (total_guests = 0 OR (no_of_adults = 0 AND no_of_children = 0)): 0

Empty DataFrame
Columns: [Booking_ID, no_of_adults, no_of_children, no_of_weekend_nights, no_of_week_nights, type_of_meal_plan, required_car_parking_space, room_type_reserved, lead_time, arrival_year, arrival_month, arrival_date, market_segment_type, repeated_guest, no_of_previous_cancellations, no_of_previous_bookings_not_canceled, avg_price_per_room, no_of_special_requests, booking_status, arrival_date_full, descriptive_room_type, descriptive_meal_plan, total_guests, total_nights]
Index: []

[0 rows x 24 columns]

In [10]:
condition_2 = (df['avg_price_per_room'] == 0) & ((df['no_of_adults'] > 0) | (df['no_of_children'] > 0))
filtered_df_2 = df[condition_2]

print(f"Number of rows with avg_price_per_room = 0 AND (no_of_adults > 0 OR no_of_children > 0): {filtered_df_2.shape[0]}")
display(filtered_df_2.head())

Number of rows with avg_price_per_room = 0 AND (no_of_adults > 0 OR no_of_children > 0): 467

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,...,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status,arrival_date_full,descriptive_room_type,descriptive_meal_plan,total_guests,total_nights
63,INN00064,1,0,0,1,Meal Plan 1,0,Room_Type 1,2,2017,...,0,0,0.0,1,1,10-09-2017,Standard Room,"Breakfast, Lunch & Dinner",1,1
145,INN00146,1,0,0,2,Meal Plan 1,0,Room_Type 1,13,2018,...,3,5,0.0,1,1,01-06-2018,Standard Room,"Breakfast, Lunch & Dinner",1,2
266,INN00267,1,0,0,2,Meal Plan 1,0,Room_Type 1,1,2017,...,0,1,0.0,1,1,12-08-2017,Standard Room,"Breakfast, Lunch & Dinner",1,2
267,INN00268,1,0,2,1,Meal Plan 1,0,Room_Type 1,4,2017,...,0,0,0.0,1,1,23-08-2017,Standard Room,"Breakfast, Lunch & Dinner",1,3
288,INN00289,2,0,0,1,Meal Plan 1,0,Room_Type 2,9,2018,...,0,3,0.0,1,1,07-09-2018,Deluxe Room,"Breakfast, Lunch & Dinner",2,1

In [11]:
rows_to_drop_count = filtered_df_2.shape[0]
df = df[~condition_2]

print(f"Dropped {rows_to_drop_count} rows where avg_price_per_room was 0 but guests were present.")
print(f"Remaining rows in DataFrame: {df.shape[0]}")

Dropped 467 rows where avg_price_per_room was 0 but guests were present.
Remaining rows in DataFrame: 35690

In [12]:
rows_to_drop_count = filtered_df_2.shape[0]
df = df[~condition_2]

print(f"Dropped {rows_to_drop_count} rows where avg_price_per_room was 0 but guests were present.")
print(f"Remaining rows in DataFrame: {df.shape[0]}")

Dropped 467 rows where avg_price_per_room was 0 but guests were present.
Remaining rows in DataFrame: 35690

/tmp/ipykernel_11594/861391035.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~condition_2]

In [13]:
df['required_car_parking_space'].unique()

array([0, 1])

In [14]:
df = df.drop(columns=['required_car_parking_space'])
print("Dropped 'required_car_parking_space' column.")
print(f"Current DataFrame shape: {df.shape}")

Dropped 'required_car_parking_space' column.
Current DataFrame shape: (35690, 23)

In [15]:
import os
if not os.path.exists('data'):
    os.makedirs('data')

df.to_csv("Hotel_Reservations_2.csv", index=False)
print("Cleaned data saved to 'Hotel_Reservations_2.csv'.")

Cleaned data saved to 'Hotel_Reservations_2.csv'.