# ML Preprocessing

## Objective

Prepare the cleaned hotel reservation dataset for machine learning model development.

Tasks:

* Load dataset
* Understand structure
* Inspect target variable
* Review feature types

In [1]:
import pandas as pd

df = pd.read_csv("../data/Cleaned_Hotel_Reservations.csv")

print("Shape:", df.shape)
df.head()

Shape: (35555, 25)

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,room_type_reserved,lead_time,arrival_year,arrival_month,...,avg_price_per_room,no_of_special_requests,booking_status,arrival_date_full,descriptive_room_type,descriptive_meal_plan,total_guests,total_nights,revenue_per_night,booking_segment
0,INN00001,2,0,1,2,Meal Plan 1,Room_Type 1,224,2017,10,...,65.00,0,1,02-10-2017,Standard Room,"Breakfast, Lunch & Dinner",2,3,21.666667,Long-Term
1,INN00002,2,0,2,3,Not Selected,Room_Type 1,5,2018,11,...,106.68,1,1,06-11-2018,Standard Room,No Meal Plan,2,5,21.336000,Last-Minute
2,INN00003,1,0,2,1,Meal Plan 1,Room_Type 1,1,2018,2,...,60.00,0,0,28-02-2018,Standard Room,"Breakfast, Lunch & Dinner",1,3,20.000000,Last-Minute
3,INN00004,2,0,0,2,Meal Plan 1,Room_Type 1,211,2018,5,...,100.00,0,0,20-05-2018,Standard Room,"Breakfast, Lunch & Dinner",2,2,50.000000,Long-Term
4,INN00005,2,0,1,1,Not Selected,Room_Type 1,48,2018,4,...,94.50,0,0,11-04-2018,Standard Room,No Meal Plan,2,2,47.250000,Medium-Term

# Dataset Inspection

Analyze dataset structure, data types and target distribution.

In [2]:
df.info()

df.describe()

print(df["booking_status"].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35555 entries, 0 to 35554
Data columns (total 25 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            35555 non-null  object
 1   no_of_adults                          35555 non-null  int64
 2   no_of_children                        35555 non-null  int64
 3   no_of_weekend_nights                  35555 non-null  int64
 4   no_of_week_nights                     35555 non-null  int64
 5   type_of_meal_plan                     35555 non-null  object
 6   room_type_reserved                    35555 non-null  object
 7   lead_time                             35555 non-null  int64
 8   arrival_year                          35555 non-null  int64
 9   arrival_month                         35555 non-null  int64
 10  arrival_date                          35555 non-null  int64
 11  market_segment_type                   35555 non-null  object
 12  repeated_guest                        35555 non-null  int64
 13  no_of_previous_cancellations          35555 non-null  int64
 14  no_of_previous_bookings_not_canceled  35555 non-null  int64
 15  avg_price_per_room                    35555 non-null  float64
 16  no_of_special_requests                35555 non-null  int64
 17  booking_status                        35555 non-null  int64
 18  arrival_date_full                     35555 non-null  object
 19  descriptive_room_type                 35555 non-null  object
 20  descriptive_meal_plan                 35555 non-null  object
 21  total_guests                          35555 non-null  int64
 22  total_nights                          35555 non-null  int64
 23  revenue_per_night                     35555 non-null  float64
 24  booking_segment                       35555 non-null  object
dtypes: float64(2), int64(15), object(8)
memory usage: 6.8+ MB
booking_status
1    23728
0    11827
Name: count, dtype: int64

# Feature Selection

Remove identifier columns and redundant features that do not contribute to prediction.

In [3]:
columns_to_drop = [
    "Booking_ID",
    "arrival_date_full",
    "descriptive_room_type",
    "descriptive_meal_plan"
]

df = df.drop(columns=columns_to_drop)

print(df.shape)

(35555, 21)

# Feature Validation

Verify remaining columns before encoding.

In [4]:
print(df.columns.tolist())

['no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights', 'type_of_meal_plan', 'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month', 'arrival_date', 'market_segment_type', 'repeated_guest', 'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled', 'avg_price_per_room', 'no_of_special_requests', 'booking_status', 'total_guests', 'total_nights', 'revenue_per_night', 'booking_segment']

# Encoding Categorical Variables

Convert categorical variables into numerical format for machine learning.

In [5]:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,...,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status,total_guests,total_nights,revenue_per_night,booking_segment
0,2,0,1,2,0,0,224,2017,10,2,...,0,0,0,65.00,0,1,2,3,21.666667,1
1,2,0,2,3,3,0,5,2018,11,6,...,0,0,0,106.68,1,1,2,5,21.336000,0
2,1,0,2,1,0,0,1,2018,2,28,...,0,0,0,60.00,0,0,1,3,20.000000,0
3,2,0,0,2,0,0,211,2018,5,20,...,0,0,0,100.00,0,0,2,2,50.000000,1
4,2,0,1,1,3,0,48,2018,4,11,...,0,0,0,94.50,0,0,2,2,47.250000,2

# Encoding Verification

Confirm all columns are ready for model training.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35555 entries, 0 to 35554
Data columns (total 21 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   no_of_adults                          35555 non-null  int64
 1   no_of_children                        35555 non-null  int64
 2   no_of_weekend_nights                  35555 non-null  int64
 3   no_of_week_nights                     35555 non-null  int64
 4   type_of_meal_plan                     35555 non-null  int64
 5   room_type_reserved                    35555 non-null  int64
 6   lead_time                             35555 non-null  int64
 7   arrival_year                          35555 non-null  int64
 8   arrival_month                         35555 non-null  int64
 9   arrival_date                          35555 non-null  int64
 10  market_segment_type                   35555 non-null  int64
 11  repeated_guest                        35555 non-null  int64
 12  no_of_previous_cancellations          35555 non-null  int64
 13  no_of_previous_bookings_not_canceled  35555 non-null  int64
 14  avg_price_per_room                    35555 non-null  float64
 15  no_of_special_requests                35555 non-null  int64
 16  booking_status                        35555 non-null  int64
 17  total_guests                          35555 non-null  int64
 18  total_nights                          35555 non-null  int64
 19  revenue_per_night                     35555 non-null  float64
 20  booking_segment                       35555 non-null  int64
dtypes: float64(2), int64(19)
memory usage: 5.7 MB

# Preparing Feature Matrix

Separate independent variables and target variable.

In [7]:
X = df.drop("booking_status", axis=1)

y = df["booking_status"]

print(X.shape)
print(y.shape)

(35555, 20)
(35555,)

# Train-Test Split

Create training and testing datasets for model development.

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(28444, 20)
(7111, 20)

WEEK 3 - MAIN ML PART

# Logistic Regression Model

Objective:
Train a Logistic Regression model to predict hotel booking cancellations.

In [12]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

lr = LogisticRegression(max_iter=5000)

lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)